"""empty message

Revision ID: 853c2de29138
Revises: 2ab57a16cbab
Create Date: 2021-03-03 17:34:39.966821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '853c2de29138'
down_revision = '2ab57a16cbab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['password'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
